### ISSUE TITLE
El .gitignore

### ISSUE THREAD

**Issue by Makova** [Rodriyeich/CRUD-Python#1]
No hace falta que tenga tanto, con esto te sobra para el ejercicio CRUD, claro:

*.log
*.csv
*~
*.#

**Comment by Makova** [comment]
Seguro que ya sabes como utilizar el gitignore.

**Comment by Rodriyeich** [comment]
Ya he hecho merge a la rama Master,

Todavía no he realizado la entrega en la plataforma del curso a la espera
de que pueda ver el proyecto. Por si yo no he entendido bien la actividad y
tenga que hacer modificaciones.

Muchas gracias por el seguimiento y el interés.

un saludo

José Manuel



2016-07-12 0:08 GMT+02:00 Manu <notifications@github.com>:
