### ISSUE TITLE
Sube ya los ejercicos

### ISSUE THREAD

**Issue by Makova** [Rodriyeich/CRUD-Python#5]
El de CRUD y ejercicio de autoevaluación del mismo tema para que pueda ponerles nota, ten en cuenta que el curso acaba el 15 de Julio y lo hemos alargado hasta final del domingo día 17 de Julio..

Saludos.

**Comment by Rodriyeich** [comment]
Ya tiene las entregas, en la entrega CRUD he subido el txt con la URL al repositorio. Si tuviera cualquier problema para acceder hágamelo saber.

Un saludo y gracias!

**Comment by Makova** [comment]
👍
